# Generated by Django 4.0.2 on 2022-02-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_centro', models.CharField(max_length=100, verbose_name='Digite o nome o centro')),
                ('sigla_centro', models.CharField(max_length=15, verbose_name='Digite a sigla do centro')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='Digite a latitude')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='Digite a longitude')),
            ],
        ),
    ]
