# Generated by Django 4.0.2 on 2022-02-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_centros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centros',
            name='latitude',
            field=models.CharField(max_length=15, verbose_name='Digite a latitude'),
        ),
        migrations.AlterField(
            model_name='centros',
            name='longitude',
            field=models.CharField(max_length=15, verbose_name='Digite a longitude'),
        ),
    ]
