# Generated by Django 4.0.2 on 2022-02-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_centros', '0002_alter_centros_latitude_alter_centros_longitude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Centros',
            new_name='Centros_Rio_Branco',
        ),
    ]
