# Generated by Django 4.0.2 on 2022-02-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_centros', '0003_rename_centros_centros_rio_branco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centros_Floresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_centro', models.CharField(max_length=100, verbose_name='Digite o nome o centro')),
                ('sigla_centro', models.CharField(max_length=15, verbose_name='Digite a sigla do centro')),
                ('latitude', models.CharField(max_length=15, verbose_name='Digite a latitude')),
                ('longitude', models.CharField(max_length=15, verbose_name='Digite a longitude')),
            ],
        ),
    ]
