# Generated by Django 4.0.2 on 2022-02-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_centros', '0004_centros_floresta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centros_floresta',
            old_name='nome_centro',
            new_name='nome_centro_fl',
        ),
        migrations.RenameField(
            model_name='centros_floresta',
            old_name='sigla_centro',
            new_name='sigla_centro_fl',
        ),
        migrations.RemoveField(
            model_name='centros_floresta',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='centros_floresta',
            name='longitude',
        ),
        migrations.AddField(
            model_name='centros_floresta',
            name='latitude_fl',
            field=models.CharField(default='', max_length=25, verbose_name='Digite a latitude'),
        ),
        migrations.AddField(
            model_name='centros_floresta',
            name='longitude_fl',
            field=models.CharField(default='', max_length=25, verbose_name='Digite a longitude'),
        ),
        migrations.AlterField(
            model_name='centros_rio_branco',
            name='latitude',
            field=models.CharField(default='', max_length=25, verbose_name='Digite a latitude'),
        ),
        migrations.AlterField(
            model_name='centros_rio_branco',
            name='longitude',
            field=models.CharField(default='', max_length=25, verbose_name='Digite a longitude'),
        ),
    ]
